AnyDSL/MimIR

.clang-format, CMakeLists.txt, dialects/CMakeLists.txt, dialects/foo.cpp, dialects/foo.h, src/driver/CMakeLists.txt, src/driver/main.cpp, src/thorin/CMakeLists.txt, src/thorin/axiom.h, src/thorin/be/ll/ll.h, src/thorin/config.h.in, src/thorin/debug.h, src/thorin/def.h, src/thorin/error.h, src/thorin/fe/lexer.h, src/thorin/fe/parser.h, src/thorin/fe/tok.h, src/thorin/lam.h, src/thorin/pass/optimize.h, src/thorin/pass/pass.cpp, src/thorin/pass/pass.h, src/thorin/tables.h, src/thorin/tuple.h, src/thorin/util/hash.h, src/thorin/util/stream.h, src/thorin/world.h
Still have to figure out Windows support
=> proof-of-concept plugin system

src/thorin/analyses/domtree.cpp, src/thorin/be/ll/ll.cpp, src/thorin/def.cpp, src/thorin/def.h, src/thorin/fe/parser.cpp, src/thorin/fe/tok.cpp, src/thorin/normalize.cpp, src/thorin/stream.cpp, src/thorin/tables.h, src/thorin/util/assert.h, src/thorin/util/stream.h, src/thorin/world.cpp, src/thorin/world.h
Uses less macro magic and hopefully silences MSVC warnings.
=> rework unreachable + breakpoint magic

cli/dialects.cpp, thorin/CMakeLists.txt, thorin/util/dlopen.cpp, thorin/util/dlopen.h
=> Move so/dll handling to util

gtest/test.cpp, thorin/analyses/scope.cpp, thorin/def.h, thorin/world.cpp
Pull request to track the progress on this bug.
=> added test case for dependent extract bug

.clang-format, .github/workflows/windows.yml, cli/main.cpp, gtest/CMakeLists.txt, gtest/for_ax.cpp, gtest/helpers.cpp, gtest/helpers.h, gtest/lexer.cpp, gtest/test.cpp, thorin/be/ll/ll.cpp, thorin/be/ll/ll.h, thorin/dialects.cpp, thorin/fe/parser.cpp, thorin/util/print.h, thorin/util/sys.cpp, thorin/util/sys.h
Let's finally figure out how to work with clang + gtest etc under Windows.
Also, I'd like to make testing thread-safe. Rn, there is a data race for the name of the test if you use `ctest -j x`.
TODO:
=> factors out a couple of common things

dialects/clos/pass/rw/clos2sjlj.cpp, dialects/core/normalizers.cpp, gtest/test.cpp, thorin/fe/parser.cpp, thorin/normalize.cpp, thorin/pass/rw/partial_eval.cpp, thorin/world.h
make tt/ff lits consistent with front-end
=> lit_true/false -> lit_tt/ff

cmake/Thorin.cmake
See 4 & 5 in https://samthursfield.wordpress.com/2015/11/21/cmake-dependencies-between-targets-and-files-and-custom-commands/
=> Hopefully fix parallel make builds.

docs/langref.md, gtest/lexer.cpp, gtest/restricted_dep_types.cpp, gtest/test.cpp, lit/type_error/domain.thorin, thorin/check.cpp, thorin/error.cpp, thorin/error.h, thorin/fe/lexer.h, thorin/fe/parser.cpp, thorin/fe/parser.h, thorin/fe/scopes.cpp, thorin/world.cpp, thorin/world.h
Also, started porting type-errors to lit testing.
=> removed different Error exceptions

thorin/check.cpp, thorin/check.h, thorin/def.cpp, thorin/def.h, thorin/tuple.cpp, thorin/tuple.h, thorin/world.cpp
More aggressive normalization/typing rules.
=> Extract type

lit/restructre_free_var.thorin, thorin/check.cpp, thorin/world.cpp
With my latest additions to Thorin's normalization/typing rules, this finally fixes @NeuralCoder3's Var problem. I included the original test case within the lit test suite.
=> fix for restructure/var problem + test case

cli/main.cpp, docs/langref.md, thorin/def.cpp, thorin/dump.cpp, thorin/fe/lexer.cpp, thorin/fe/parser.cpp, thorin/fe/scopes.h, thorin/fe/tok.h, thorin/world.h
Adds syntactic sugar for defining "inline" curried functions.
=> Curried Function

dialects/core/be/ll/ll.cpp, dialects/core/core.h, dialects/core/normalizers.cpp, dialects/mem/mem.h, dialects/mem/normalizers.cpp, dialects/mem/passes/fp/ssa_constr.cpp, thorin/axiom.h
Just a shortcut for `match<Id, false>(...)`: `force<Id>(...)`.
=> shortcut: force<Id>(...) = match<Id, false>(...)

lit/direct/ds2cps_ax_cps2ds_dependent2.thorin
Added a conversion for 42.
Closes #106
=> Fix for ds2cps_ax_cps2ds_dependent2.thorin

lit/core/unary_tuple.thorin, thorin/world.cpp
=> unary tuple fix

dialects/core/be/ll/ll.cpp, dialects/mem/mem.h, dialects/mem/mem.thorin, lit/mem/alloc_load_store.thorin, lit/mem/malloc_load_store.thorin
just adding mem::free for deallocating memory from alloc & malloc.
=> Implementing mem::free

thorin/be/emitter.h, thorin/def.h, thorin/phase/phase.cpp, thorin/phase/phase.h, thorin/rewrite.cpp, thorin/rewrite.h
Currently working on closure stuff and wanted to port some of the phases to `RWPhase` to remove code duplication. My initial idea didn't work out so well, so I refactored and simplified a couple of things. Let's see where this is going.
=> just refactoring/simplifiny a couple of rewrite related things

thorin/analyses/schedule.cpp, thorin/be/emitter.h, thorin/check.cpp, thorin/def.cpp, thorin/def.h, thorin/lam.h, thorin/pass/pass.cpp, thorin/phase/phase.cpp, thorin/world.cpp
See comment in set/unset ops.
Fixes #134
=> Simplifies Def::is_set and softens assert

lit/rec_pi.thorin, thorin/axiom.cpp
Bug fix for axioms regarding recursive function types.
=> bugfix: detetect recursive function types in axioms

.github/workflows/macos.yml
=> [CI][OSX] Override python path for CMake.

thorin/def.cpp
Bug fix for `Axiom::rebuild` - see #155.
=> fixes #155

dialects/clos/pass/rw/branch_clos_elim.h, dialects/clos/pass/rw/clos_conv_prep.cpp, dialects/clos/pass/rw/clos_conv_prep.h, dialects/core/normalizers.cpp, dialects/mem/passes/rw/reshape.cpp, dialects/mem/phases/rw/add_mem.cpp, thorin/flags.h, thorin/pass/rw/lam_spec.cpp
Fixes a couple of issues while making impala work again with latest changes in thorin/master.
* some places were missing the new Nat flag for bit1/bit2
* Hack flag for impala to make LamSpec more aggressive
* ignore Global in some places
=> various bugfixes

dialects/core/core.thorin, dialects/core/normalizers.cpp, lit/core/idx.thorin, thorin/dump.cpp
=> added %core.idx axiom + test case

dialects/refly/normalizers.cpp, dialects/refly/passes/remove_perm.cpp, dialects/refly/refly.thorin, lit/refly/debug.thorin, lit/refly/debug_perm.thorin, lit/refly/refine.thorin
* `%refly.Code` is now a type constructor: `* -> *`
* adjusted signatures
* using type inference
* `%refly.dbg` now additionally expects a log level
* updated lit tests
=> Infer refly

dialects/direct/passes/cps2ds.cpp, lit/fun.thorin, lit/pack.thorin, thorin/fe/parser.cpp, thorin/tuple.h
+ test case
+ small bug fix in cps2ds
=> implemented proper parsing of packs

.github/workflows/macos.yml
This fixes the issue with `macos-latest`
=> [CI] Use release-downloader on MacOS

.github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, docs/coding.md, lit/CMakeLists.txt
* renamed target check -> lit to avoid a name clash
=> update absl to lts_2023_08_02

dialects/core/normalizers.cpp, lit/core/sub_bug.thorin
=> fix #253 + test case

include/thorin/normalize.h, plugins/core/src/thorin/plug/core/normalizers.cpp, plugins/math/src/thorin/plug/math/normalizers.cpp
=> Normalize h

gtest/test.cpp, include/mim/plug/tuple/tuple.h, lit/refly/equiv.mim, lit/tuple/concat.mim, src/mim/ast/emit.cpp, src/mim/plug/CMakeLists.txt, src/mim/plug/core/core.mim, src/mim/plug/core/normalizers.cpp, src/mim/plug/refly/normalizers.cpp, src/mim/plug/refly/refly.mim, src/mim/plug/tuple/CMakeLists.txt, src/mim/plug/tuple/normalizers.cpp, src/mim/plug/tuple/tuple.cpp, src/mim/plug/tuple/tuple.mim, src/mim/world.cpp
There are still some issues with type inference. Hence, I'm overriding the implicits with `@` at some call sites. But this is an issue for another day.
=> wip: tuple.concat, tuple.prepend, tuple.append

cmake/Mim.cmake, docs/coding.md, include/mim/ast/ast.h, include/mim/rewrite.h, include/mim/world.h, lit/tuple/normalize.mim, src/mim/ast/emit.cpp, src/mim/ast/parser.cpp, src/mim/cli/main.cpp, src/mim/def.cpp, src/mim/plug/affine/pass/lower_for.cpp, src/mim/plug/tuple/normalizers.cpp, src/mim/plug/tuple/tuple.mim, src/mim/plug/vec/normalizers.cpp, src/mim/rewrite.cpp, src/mim/world.cpp
* better bootstrapping
* added watchpoints
* porting affine improvements
* misc ports
=> fixing various issues

src/mim/driver.cpp
Removes the feature to specify a filename for a plugin directly. This is a confusing feature anyway and nobody uses it.
Fixes #325
=> fix for #325
