AnyDSL/MimIR

LICENSE.TXT

I'm currently in the process of relicensing Thorin2 to use MIT license instead of LGPL-3. I did a manual audit of the code to ensure that each line of code is either *trivial* or was written/rewritten by:
*Trivial* in this context means:
* empty lines
* lines only containing comments, parenthesis, braces, `namespace` directives, `include` directives, etc. 
* API declarations
I (@leissa) hereby give permission to change the license to MIT.
I'm kindly asking @madmann91, @richardmembarth, @f-fries to give their permission for the license change. Please let me know in the comments below :)

Relicense to MIT

---

CMakeLists.txt
gtest/test.cpp

With this the tests can can call std::system to compile the LLVM IR files using clang and execute them.

Disable vagrant for sub-processes.

---

docs/coding.md
thorin.natvis

Shows the node type in string form directly for each Def. For Axioms, it shows the axiom's tag.
Additionally, the ops are shown as array elements. These are otherwise not inspectable "sanely" at all.
Can be greatly expanded, but this was what I needed today :)
Exemplary view:

Add some initial Natvis file to make debugging thorin in VS Code less painful

---

.gitignore
gtest/CMakeLists.txt
gtest/for_ax.cpp
gtest/test.cpp
src/thorin/CMakeLists.txt
src/thorin/be/ll/ll.cpp
src/thorin/pass/rw/lower_for.cpp
src/thorin/pass/rw/lower_for.h
src/thorin/tables.h
src/thorin/world.cpp
src/thorin/world.h

This adds a `For` axiom including a `LowerFor` rewrite pass that lowers the axiom to a CPS loop.
The axiom is defined following this scheme:
` for :: [m: Nat , n: Nat , Ts: «n; *»] → [Mem , Int m, Int m, Int m, «i: n; Is#i», Cn [Mem , «i: n; Is#i», Cn [Mem , «i: n; Is#i»]], Cn [Mem , «i: n; Is#i»]];`
Note, that due to 1. the design of the return cn (doesn't have a continuation itself) and 2. some _unexpected_ indirection, the LL backend currently requires all passes including `CopyProp` to run in an optimization phase after the lowering. Otherwise, assertion failures/crashes occur.
Happy about any feedback!

Add affine for-loop axiom

---

gtest/for_ax.cpp
src/thorin/pass/rw/lower_for.cpp
src/thorin/pass/rw/lower_for.h

With this in place, LowerFor can be used in the same PM as CopyProp.

LowerFor should cache the rewritten axioms.

---

thorin/CMakeLists.txt
thorin/be/dot/dot.cpp
thorin/be/dot/dot.h

This adds back an option to view the thorin graph. Note, the nodes are clustered into lams following the emitter's schedule.
As an example, the output from the `ForSteps/ForAxiomTest.for_dynamic_iters/17` test after the opt phase:
While this is somewhat crude and the text inside the nodes maybe isn't ideal as well (basically `def->dump(0)`), it should help with debugging then and when. The nodes' content can be customized using an optional function parameter for `dot::emit`.

Add some backend-style dot emitter.

---

CMakeLists.txt
cli/CMakeLists.txt
cmake/Thorin.cmake
cmake/thorin-config.cmake.in
dialects/CMakeLists.txt
thorin/CMakeLists.txt

I did not change the directory layout of thorin for now. Some things I'd preferably change, like the fact that we pollute the `include` folder with `dialects`. Also, we could remove some matching overhead if we had a single `include` folder, but it's not an incredible overhead.
This installs thorin to `CMAKE_INSTALL_PREFIX` with the following structure:
```
bin
\ thorin
include
\ absl
\ dialects
\ thorin
\ half.hpp
lib
\ cmake
\ absl
\ *.cmake
\ thorin
\ thorin-config.cmake
\ thorin-config-version.cmake
\ thorin-targets-[debug|release].cmake
\ thorin-targets.cmake
\ Thorin.cmake
\ thorin
\ *.thorin
\ libthorin_*.so
\ libabsl_*.so
\ libthorin.so
```
After installing, external dialects just need to find the package:
```
cmake_minimum_required(VERSION 3.20 FATAL_ERROR)
project(dialect) …
```

Add `make install` support.

---

docs/langref.md
lit/affine/lower_for.thorin
lit/core/normalize_add.thorin
lit/core/normalize_and_ff.thorin
lit/core/normalize_and_ff_tt.thorin
lit/core/normalize_and_icmps.thorin
lit/core/normalize_and_icmps_lit.thorin
lit/core/normalize_and_tree.thorin
lit/core/normalize_and_tt.thorin
lit/core/normalize_and_tt_tt.thorin
lit/core/normalize_icmp.thorin
lit/core/ret_add.thorin
lit/core/ret_and.thorin
lit/core/ret_lshr.thorin
lit/main_loop.thorin
lit/main_loop_nom.thorin
lit/mem/alloc_load_store.thorin
lit/mem/malloc_load_store.thorin
lit/mem/mslot_load_store.thorin
lit/mem/slot_load_store.thorin
lit/parse_output_parse.thorin
lit/ret_argc.thorin
thorin/error.cpp
thorin/fe/parser.cpp
thorin/fe/parser.h
thorin/stream.cpp
thorin/world.cpp
thorin/world.h

This should make most thorin output (that only uses known axioms) parsable by the frontend.
Very likely still a bunch of cases not correct...
To simplify outputting nom var names, the parser now supports reading a list of var names after the nom's type.
The proposed syntax (to disambiguate from ops) is `.lam name : type, @(var0, var1) = {..};`
Known issues:
- nominal sigmas are emitted as `.Sigma name : type, #ops, @(var,..) = { [..] };`, which cannot be parsed at the moment. To support this, we either need integrated special cases in `parse_nom` and `parse_def` (similar to `parse_sigma`), or great infer support (where even the types of the infer nodes are unknown until parsing the definition..)

Make thorin output parsable by frontend.

---

cli/main.cpp
cmake/Thorin.cmake
docs/cli.md
docs/langref.md
lit/affine/dynamic_for.thorin
lit/affine/for_2acc.thorin
lit/affine/for_2acc_2types.thorin
lit/affine/for_2acc_real.thorin
lit/affine/lower_for.thorin
lit/core/normalize_add.thorin
lit/core/normalize_and_ff.thorin
lit/core/normalize_and_ff_tt.thorin
lit/core/normalize_and_icmps.thorin
lit/core/normalize_and_icmps_lit.thorin
lit/core/normalize_and_tree.thorin
lit/core/normalize_and_tt.thorin
lit/core/normalize_and_tt_tt.thorin
lit/core/normalize_bitcast.thorin
lit/core/normalize_icmp.thorin
lit/core/ret_add.thorin
lit/core/ret_and.thorin
lit/core/ret_lshr.thorin
lit/main_loop.thorin
lit/main_loop_nom.thorin
lit/mem/alloc_load_store.thorin
lit/mem/malloc_load_store.thorin
lit/mem/mslot_load_store.thorin
lit/mem/slot_load_store.thorin
lit/parse_output_parse.thorin
lit/ret_argc.thorin

Also removes the -o/--output option. Instead, simply directly specify
the output file and backend via --output-h <file> etc.

remove -e/--emit option from cli

---

CMakeLists.txt

From abseil release notes:
> CMake builds now use the flag ABSL_BUILD_TESTING (default: OFF) to
> control whether or not unit tests are built.
So, BUILD_TESTING/BUILD_TESTING_BACKUP trickery not necessary anymore :)

bump abseil and googletest versions

---

cli/main.cpp
dialects/core/be/ll/ll.cpp
thorin/CMakeLists.txt
thorin/be/emitter.h
thorin/pass/pass.h
thorin/stream.cpp
thorin/util/assert.h
thorin/util/log.cpp
thorin/util/log.h
thorin/world.cpp
thorin/world.h

This puts logging stuff into it's own class and simply makes Log::level
and Log::ostream public and removes getters/setters.

refactor world logging stuff

---

dialects/affine/affine.thorin
dialects/affine/passes/lower_for.cpp
dialects/affine/passes/lower_for.h
dialects/core/be/ll/ll.cpp
lit/affine/dynamic_for.thorin
lit/affine/for_2acc.thorin
lit/affine/for_2acc_2types.thorin
lit/affine/for_2acc_real.thorin
lit/affine/for_over_mem.thorin
lit/affine/lower_for.thorin

Remove mem parameter from affine.For and its body / break cns. If a mem parameter is required, it can be propagated through the accumulator.
While at it, also removed the hard dependency on CopyProp & LamSpec by directly reducing the continuations into the lamdas.
cc  @NeuralCoder3

Refactor affine.For.

---

dialects/direct/passes/ds2cps.cpp
dialects/direct/passes/ds2cps.h
lit/direct/ds2cps_mixed_tuple.thorin
thorin/util/array.h

DS2CPS both currently either bail or fail if a loop matches their patterns.
DS2CPS just died of a stack overflow due to infinitely following the loop recursion.
DS2CPS should generally be a bit more stable now.
One major downside of this change is, that when having a loop, we must not set the PE filter to true, but without doing so, we introduce some unnecessary overhead for the non-loop cases.
Note, the loop support greatly depends on copyprop being able to propagate the continuations through branches, which I removed from this patch.

Make DS2CPS more robust

---

docs/langref.md
lit/prec.thorin
thorin/fe/parser.cpp
thorin/fe/tok.h

Adds another prec level so this one works as expected:
```
.lam .extern h x: .Nat -> .Nat = x;
```

bug fix: precedence with arrow and lam/cn

---

dialects/core/be/ll/ll.cpp
lit/core/pow.thorin
thorin/fe/parser.cpp
thorin/pass/optimize.cpp
thorin/pass/optimize.h
thorin/pass/pipelinebuilder.cpp
thorin/pass/pipelinebuilder.h

A new optimization pipeline.
The new pipeline is a strict superset of the old one and exposes at least all of the old interfacing functions.
The optimizations proceed in a pipeline ordered by priorities
Each phase is a sequence of passes that are run interleaved
The passes are added to the phase ordered by their priority
``` 
Order:
1-10: initial passes
100: Main optimization phase (default for extend_opt_phase)
200: Pre-CodeGen Optimization
300: CodeGen Preparation (default for extend_codegen_prep_phase)
concrete phases:
0  : Scalarize
1  : EtaRed
2  : TailRecElim
100: Optimize (Priority 50)
PartialEval
BetaRed
EtaRed
EtaExp
Scalarize
TailRecElim
+ Custom (default priority 100)
200: LamSpec
300: RetWrap (Priority 50)
+ Custom (default priority 100)
``` 
Note: This is still not ideal. …

Optimize pipeline

---

dialects/CMakeLists.txt
dialects/demo/demo.cpp
dialects/demo/demo.h
dialects/demo/demo.thorin
dialects/demo/normalizers.cpp
lit/CMakeLists.txt
lit/demo/const.thorin

A simple demo dialect without any passes or fancy stuff.
The dialect just adds the axiom
`%demo.constIdx: Π [n:.Nat] -> .Idx n`
and a single test case.
The axiom is resolved to `42` by its normalizer.
This PR addresses #93

Demo dialect

---

dialects/core/be/ll/ll.cpp
lit/core/ret_nand.thorin

Correct way to do it is:
```
xor -1, x
```
and **NOT**
```
xor 0, x
```
Also added codegen for bit1

bug fix in llvm for generating certain not operations

---

dialects/affine/affine.h

Mem is now handled in the acc and is therefore obsolete in the op_for call.

Remove mem from affine::op_for

---

.github/workflows/linux.yml
CMakeLists.txt
lit/CMakeLists.txt
lit/lit.site.cfg.py.in

As discussed in #105: adds a flag to replace `%thorin`  in LIT tests with `valgrind <flags> thorin` instead of just `thorin`.
As running this for Release seems feasible, it is activated in the Linux Release CI.
Fixes #105.

Enable valgrind for LIT tests

---

thorin/phase/phase.cpp
thorin/phase/phase.h

The old `RWPhase` needed to always rewrite everything as it filled a new world. This makes it difficult to **not** rewrite anything. With this change, you can simply opt to return the original def to stop recursing.

RWPhase that writes into the same world

---

.github/workflows/macos.yml

Pin the MacOS runner to MacOS 11.x, since the 12.x makes the download-release-asset action fail.
Since I don't know much about Node.JS I opened an issue against the action's repo: https://github.com/i3h/download-release-asset/issues/9

[CI] Downgrade MacOS Runner to 11 for now

---

cmake/Thorin.cmake
thorin/driver.cpp
thorin/util/dl.cpp
thorin/util/dl.h

MinGW + Win uses lib as prefix which breaks our assumption in `dl::prefix`. This patch simply overrides the prefix to always use "lib" regardless of OS/compiler.

always use "lib" as prefix

---

dialects/core/core.h
dialects/core/normalizers.cpp
dialects/math/math.h
dialects/math/normalizers.cpp
docs/Doxyfile.in
gtest/test.cpp
thorin/be/h/bootstrap.cpp
thorin/def.h
thorin/fe/scopes.cpp
thorin/util/sym.h
thorin/util/util.h
thorin/world.h

```c++
enum class E {
A = 1,
B = 2,
C = 4,
};
THORIN_ENUM_OPERATORS(E)
//...
auto x = E::A | E::B;
auto y = x ^ E::C;
```
Also switching to scoped `enum`s at some spots like `core::Mode`, `math::Mode`, etc.

macro to declare all kind of operators for enums

---

dialects/matrix/passes/lower_matrix_mediumlevel.cpp
docs/langref.md
lit/fun.thorin
thorin/check.cpp
thorin/check.h

* finally type checking for mutable Lams
* fixed bug in alpha-equiv - related to #174?
* fixed bug in lower_matrix_mediumlevel.cpp (wrong filter type)
* fixed type inference for things like `umax(0, ?) == 1`

type check lambdas when last op (body) is set

---

dialects/mem/passes/rw/reshape.cpp

The `_reshape` suffix for reshape should not be applied to externals.
See #223

Avoid renaming externals in reshape

---

dialects/core/be/ll.cpp
dialects/regex/regex.thorin
lit/regex/match_woptionals.thorin
lit/regex/match_wstar.thorin

Currently, we would generate an array, store that, calculate the offset with a GEP and then load from the GEP.
LLVM does an awful job optimizing this (potentially due to missing alias info or so).
That's why I initially resorted to actually using if/else in the regex impl, but that is also not optimized too neatly.
Therefore, I added a specialization for 2-element integral tuples (yeah, should work for a bunch of other types as well), to emit a `select` instruction instead.
On the regex benchmark, this gives a performance upgrade of ~14% speedup, leaving only a 13% slowdown compared to the manual version.
Old:
```
engine,average[us],min[us],max[us],deviation[%],
thorin,1119,1103,1150,4,
manual,861,839,891,6,
```
New:
```
engine,average[us],min[us],max[us],deviation[%],runs[us] …
```

Specialize (.Idx, .Idx)#cond to generate a select instruction.

---

dialects/clos/clos.thorin
dialects/compile/compile.cpp
dialects/compile/compile.thorin
dialects/direct/passes/cps2ds.cpp
dialects/mem/mem.thorin
dialects/opt/opt.thorin
thorin/fe/parser.cpp
thorin/pass/rw/scalarize.cpp
thorin/pass/rw/scalarize.h
thorin/tuple.cpp
thorin/tuple.h

If you are juggling around large tuples, compile time will explode. This threshold, will not scalarize tuples larger than the given threshold.

introduced threshold for Scalerize Pass

---

src/mim/plug/core/normalizers.cpp

As discussed ,adding the normalizations a+a = 2*a and a - a = 0
This makes the nat normalizer equivalent to the wrap one. 
If it is not needed, feel free to reject.

Expand normalizer for nats
